### ISSUE TITLE
Update frequency as config option (?)

### ISSUE THREAD

**Issue by nickdos** [safepay/sensor.willyweather#2]
Would be nice to be able to set a different update frequency to the hard-coded 30 minutes.

**Comment by safepay** [comment]
The minimum update frequency is set at 30 minutes because the Bureau data updates in 30 minute intervals.
You can edit the custom component number from 30 to something less if you want.
Then use the scan_interval feature in HA to change it to anything above the minimum.
Even at the moment you can increase the interval by providing a scan_interval above 30 minutes (ie > 1800 seconds).

**Comment by safepay** [comment]
As scan_interval is already in HA this is not an issue as such. More a decision around the minimum time between updates.
As the data is only updated every 30 minutes, I would prefer to leave this as the minimum and default time.
If anyone wants a lower interval, edit the sensor.py file and change the 30 minutes to less.
